<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_item_list</name>
   <tag></tag>
   <elementGuidId>b28674fe-3e07-48de-a0af-fd58832f9c96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='items-list']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#items-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>items-list</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COVID19(AgencyFIND)COVID001Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea co..COVID19(AgencyDirect)COVID001Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea co..COVID(AgencyFIND)COVID001Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea co..COVID(AgencyDirect)COVID001Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea co..item1600990526123456Random Descriptionuploaded in Automated Immunoassay subcattestEx-works: USD $120.00 (Indicative)testCovid19 category _item AtestSputnik000Ex-works: USD $4.00 (Indicative)sampleRapid Kit 0001RPD0001Ex-works: USD $3.50 (Indicative)sampleitem1598418357123456Random DescriptionCovid 19 Rapid Test KitEx-works: USD $150.00 (Indicative)test Descriptionitem1598404900123456Random Descriptionitem1598403415123456Random DescriptionItem Covid19 StockItem Covid19 StockCovidItem1123CovidItem1XPRSARS-COV2-10Ex-works: USD $198.00 (Indicative)Cost per kit (10 tests). A rapid, near-patient test for the detection of the 2019 novel coronavirus that causes COVID-19
Cepheid has developed an automated molecular test for the qualitative detection of SARS-CoV-2,..FacemasksA surgical mask is a loose-fitting, disposable device that creates a physical barrier between the mouth and nose of the wearer and potential contaminants in the immediate environment. These are often referred to as ..Rapid Test KitThis novel coronavirus disease COVID-19 IgM Rapid Test Kit is based on double sandwich lateral flow immunoassay to detect total antibody of SARS-COV-2. It can be used as an aiding tool for RT-PCR testing. Clinical d..SARS-CoV-2 Nucleic Acid TestEx-works: USD $240.00 (Indicative)48 tests/kit. STANDARD M nCoV Real-Time Detection KitEx-works: USD $1,632.00 (Indicative)96 / kit. RIDA® GENE SARS-CoV-2 RUO (PG6815RUO)Ex-works: USD $429.53 (Indicative)-genesig Real-Time PCR COVID-19Ex-works: USD $1,034.97 (Indicative)96 tests/kit.RADI COVID-19 Detection Kit and RADI COVID-19 Triple Detection Kit-Ex-works: USD $800.00 (Indicative)100 tests/kit.The Novel Coronavirus (2019-nCoV) Nucleic Acid Test KitEx-works: USD $767.01 (Indicative)96 tests/kit. VIASURE SARS-CoV-2 S gene Real Time PCR Detection KitEx-works: USD $872.23 (Indicative)96 rxns. VIASURE SARS-CoV-2 Real Time PCR Detection KitEx-works: USD $872.23 (Indicative)96 rxns. SARS-COV-2 R-GENE® (ref 423720)Ex-works: USD $872.23 (Indicative)-SARS-COV-2 R-GENE® (ref 423717)Ex-works: USD $872.23 (Indicative)-Real-time fluorescent RT-PCR kit for detecting 2019 nCoVEx-works: USD $750.00 (Indicative)50 tests/kit. Atila iAMP COVID-2019 Detection KitEx-works: USD $1,299.00 (Indicative)100 tests/kit. Allplex 2019-nCoV assayEx-works: USD $18.13 (Indicative)-</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;items-list&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='items-list']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react_0HM3381N2O7B3']/div/div/div[2]/div/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Molecular diagnostic'])[1]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G6PDd RDT'])[1]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
