<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filter_tag</name>
   <tag></tag>
   <elementGuidId>59eaf167-e20f-44ee-ad3c-cbd79f093c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react_0HM3381N2O7B3']/div/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pull-left.filter-tag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-left filter-tag</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALL CATEGORIES Search >  COVID-19 diagnostics  Antigen (Ag) RDTManual immunoassay/ELISAAutomated immunoassay/ELISAAntibody (Ab) RDTManual immunoassay/ELISAAutomated immunoassay/ELISAMolecular assays (NAT) AutomatedManualSelf-collection kitSequencingMolecular diagnostics (centralized, cartridge-based, line probe assays)Liquid cultureSolid culture Rapid speciation (RDT kits) LTBI (IGRA, Skin tests)LAM (Urine LAM)Chest Xray (stationary systems, portable systems, CAD)Stool processing solutions MicroscopyPPEGlucose meters Strips LancetsRDTsAutomated molecular tests 2020Manual molecular tests 2020Supplemental assaysEnzyme immunoassays Self-testsPlatforms Cartridges RDTsImmunoassaysMolecular testsInstrumentsReagentsAntigen RDTs 2020G6PDd analyzerG6PDd test deviceG6PDd RDTMolecular diagnostic31 items found</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HM3381N2O7B3&quot;)/div[1]/div[@class=&quot;combined-collection&quot;]/div[@class=&quot;item-list-section&quot;]/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;pull-left filter-tag&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react_0HM3381N2O7B3']/div/div/div[2]/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procure through FIND'])[2]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procure directly from seller'])[2]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
